INCLUDE = -I..

32:
	$(CC) -m32 $(INCLUDE) ../stb_vorbis.c test_c_compilation.c -lm
	$(CC) -m32 $(INCLUDE) ../stb_vorbis.c test_cpp_compilation.cpp -lm

64:
	$(CC) -m64 $(INCLUDE) ../stb_vorbis.c test_c_compilation.c -lm
	$(CC) -m64 $(INCLUDE) ../stb_vorbis.c test_cpp_compilation.cpp -lm
